## Tensors:
- Data structure
- Very similar to array matrices & NumPy's ndarrays
    - Tensors can run on GPUs/other specialized hardware to accelerate computing
- Used to encode I/O & parameters of a model 

In [1]:
import torch
import numpy as np

## Tensor Initialization

### Directly from data

In [5]:
# Creating matrices w/ array
data = [
    [1, 2],
    [3, 4]
       ]

In [6]:
x_data = torch.tensor(data)

### From a NumPy array

In [7]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [8]:
x_np

tensor([[1, 2],
        [3, 4]])

### From another tensor

In [10]:
x_ones = torch.ones_like(x_data)
print(f"{x_ones}\n")

tensor([[1, 1],
        [1, 1]])



In [12]:
x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f"{x_rand}\n")

tensor([[0.6804, 0.6062],
        [0.3478, 0.5479]])

